// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY6KziYKSXpQJQzLipJmtMi0XstX5mXIE',
    appId: '1:221823830483:web:f443599e8fe2e1471a0726',
    messagingSenderId: '221823830483',
    projectId: 'places-app-7ee6f',
    authDomain: 'places-app-7ee6f.firebaseapp.com',
    databaseURL: 'https://places-app-7ee6f-default-rtdb.firebaseio.com',
    storageBucket: 'places-app-7ee6f.appspot.com',
    measurementId: 'G-DD8CQ9HRX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7X3yezeGKdQQwa5JB0h9CFt7QuxznO6s',
    appId: '1:221823830483:android:01de461660e531471a0726',
    messagingSenderId: '221823830483',
    projectId: 'places-app-7ee6f',
    databaseURL: 'https://places-app-7ee6f-default-rtdb.firebaseio.com',
    storageBucket: 'places-app-7ee6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbpbhFIBhwVMDvohQLwJzkOHIq7Mk58tQ',
    appId: '1:221823830483:ios:872f13e097aee2181a0726',
    messagingSenderId: '221823830483',
    projectId: 'places-app-7ee6f',
    databaseURL: 'https://places-app-7ee6f-default-rtdb.firebaseio.com',
    storageBucket: 'places-app-7ee6f.appspot.com',
    iosClientId: '221823830483-antvioj6888jb89tiqkapqitsic6sjr8.apps.googleusercontent.com',
    iosBundleId: 'com.example.tybaApp',
  );
}
